# Build on all three platforms
strategy:
  matrix:
    linux:
      imageName: 'ubuntu-22.04'
      buildosname: 'linux'
      outputArchiveType: 'tar'
      outputArchiveExtension: 'tar.gz'
    mac:
      imageName: 'macos-latest'
      buildosname: 'macos'
      outputArchiveType: 'tar'
      outputArchiveExtension: 'tar.gz'
    windows:
      imageName: 'windows-2019'
      buildosname: 'windows'
      outputArchiveType: 'zip'
      outputArchiveExtension: 'zip'

pool:
  vmImage: $(imageName)

steps:
- checkout: self
  submodules: true
  persistCredentials: false
  displayName: 'ensure hotfixes repo is checked out'
  
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'

- script: pip install -r requirements.txt
  displayName: 'Install requirements'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath' # Options: filePath, inline
    scriptPath: create_offline_installer.py
    #arguments: # Optional
  displayName: 'Create Offline installer'

- task: ArchiveFiles@2
  displayName: 'Archive webcsd-csp miniconda archive'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/output/webcsd-csp-miniconda3-$(miniconda_installer_version)-$(Build.BuildId)-$(buildosname)'
    archiveFile: '$(Build.ArtifactStagingDirectory)/webcsd-csp-miniconda3-$(miniconda_installer_version)-$(Build.BuildId)-$(buildosname).$(outputArchiveExtension)'
    archiveType: '$(outputArchiveType)'

- task: ArchiveFiles@2
  displayName: 'Archive miniconda archive'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/output/miniconda3-$(miniconda_installer_version)-$(Build.BuildId)-$(buildosname)'
    archiveFile: '$(Build.ArtifactStagingDirectory)/miniconda3-$(miniconda_installer_version)-$(Build.BuildId)-$(buildosname).$(outputArchiveExtension)'
    archiveType: '$(outputArchiveType)'

# Upload artifactory build info
- powershell: |
    $filename = Get-ChildItem -Path $(Build.ArtifactStagingDirectory) -Filter { '*.zip', '*.tar.gz' } | Select-Object -ExpandProperty Name
    Write-Host "Filename: $filename"
    if ($filename -match "miniconda3-(py[0-9]+)_") {
      $PythonVersion = $Matches[1]
      Write-Host "Python version: $PythonVersion"
      Write-Host "##vso[task.setvariable variable=PythonVersion]$PythonVersion"
    }
    else {
      Write-Error "Unable to extract Python version from filename"
    }
  displayName: 'Extract Python version and set upload path'

- task: ArtifactoryGenericUpload@2
  inputs:
    artifactoryService: 'devops-ccdc-3rd-party'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "$(Build.ArtifactStagingDirectory)/miniconda3*",
            "target": "ccdc-3rdparty-python-interpreters/miniconda3/$(PythonVersion)/"
          }
        ]
      }
    replaceSpecVars: true
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)-$(buildosname)'
    module: 'miniconda3/$(buildosname)'
    includeEnvVars: true
    failNoOp: true
  displayName: 'Upload distribution to artifactory'

- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'devops-ccdc-3rd-party'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)-$(buildosname)'
    excludeEnvVars: '*password*;*secret*;*key*;*token*'
  displayName: 'Publish build'
