---
# Build a PythonAPI container from the miniconda installer in artifactory
name: Build Python API container

on:
  repository_dispatch:
    types: [teamcity_finish]

env:
  DOCKER_BUILD_CONTEXT: './deployments/docker/'

jobs:
  build-python-api-container-from-artifact:

    runs-on: ubuntu-latest

    steps:
      - name: bad boi
        run: echo "${{ secrets.ARTIFACTORY_GH__READ_ONLY_EXPORT }}"
